### ISSUE TITLE
Support Getting JWT From Header

### ISSUE THREAD

**Issue by bestickley** [TCatshoek/fastapi-nextauth-jwt#13]
Hi, I'm running Next.js with NextAuth/Authjs on abc.com and FastAPI on 123.com. When `__Secure-authjs.session-token` cookie is set on abc.com and I attempt to perform a `fetch` to 123.com with `credentials: "include"` ([docs](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#including_credentials)), the JWT is not included in the request. When cookies are set with `Set-Cookie` they are scope to a domain. So my workaround is to create a Next.js Server Action to get the raw JWT on the frontend and send it in a header: authjs.session-token.

The issue now is that `from fastapi_nextauth_jwt import NextAuthJWT` has no way of customizing how the JWT is retrieved from the FastAPI request. Could this feature be added? Here is a proposed API:

```py
app = FastAPI()

JWT = NextAuthJWT(
    secret="y0uR_SuP3r_s3cr37_$3cr3t",
    get_jwt= lambda r: r.headers['authjs.session-token']
)

@app.get("/")
async def return_jwt(jwt: Annotated[dict, Depends(JWT)]):
    return jwt
```

Thank you for your consideration!

**Comment by TCatshoek** [comment]
Hi! 

Would an [external url rewrite](https://nextjs.org/docs/pages/api-reference/next-config-js/rewrites#rewriting-to-an-external-url) work for this? 

You could have something like

```javascript
module.exports = {
  async rewrites() {
    return [
      {
        source: '/api/:slug',
        destination: 'https://123.com/:slug',
      },
    ]
  },
}
```

and then do a fetch to `/api/something` with `credentials: "include"` which nextjs will proxy to `https://123.com/something` for you. 

Hopefully that would then include the cookie like normal, although I'm not 100% sure it would just from the top of my head.

Another option could be maybe making a dynamic route at for example like `/app/api/proxy/[[...slug]]/route.ts` and copying over the headers (which should include the cookies):

```javascript


const BASE_URL = "http://fastapi-test.com:8000" // Get from env or something

export async function GET(
    request: Request,
    { params }: { params: { slug: string[] | undefined } })
{
    const proxyPath = params.slug?.join("/") || ""
    const proxyUrl = new URL(proxyPath, BASE_URL)

    return await fetch(proxyUrl, {
        headers: request.headers,
        credentials: "include"
    })
}
```

**Comment by bestickley** [comment]
@TCatshoek, thank you for proposing those alternatives! While that might be able to work, those are not ideal because:
1) I'm running Next.js and Python Fast API on separate AWS Lambda functions so I'd be paying for double the lambda compute during the request. The Python Fast API is interacting with an LLM which takes a while exaggerating the 2x cost
2) The Python Fast API returns a streaming a response so Next.js would have to ensure the response is streamed as well. Not sure, but that might be tricky.

Make sense?

**Comment by TCatshoek** [comment]
Ah I see. In that case, I would set them up so the fastapi lambda is on a subdomain of the nextjs one, and configure nextauth to allow sharing cookies with subdomains.

I wouldn't recommend exposing the whole token to the frontend/JS side since there are security implications to doing so. (Effectively the session cookies wouldn't be httponly anymore)

**Comment by bestickley** [comment]
@TCatshoek, you're right. Going to use subdomain approach. Thank you for your thoughts!
