### ISSUE TITLE
id should be string?

### ISSUE THREAD

**Issue by AndyMik90** [TCatshoek/fastapi-nextauth-jwt#6]
Given the simple example, should `async authorize(credentials, req) {
                if (credentials) {
                    return {id: 1, name: credentials.username, email: "test@test.nl"}
                }
                // Return null if user data could not be retrieved
                return null`

use id as a string?

**Comment by TCatshoek** [comment]
Hi Andy,

I think you're right, looking at the type definitions in nextauth, id should be a string here! 

Thanks for reporting this
